// Accept function pointer, elapse time, accept start time
// property struct generated by passed stuff
// Manage queue

// Actually run the functions with the function pointers
// Deploy threads

class TaskScheduler {
public:
    // Gets the function pointer, elapse time and start time if applicable
    void addTask();
private:
    // Makes a structure from the passed information
    int createTask();
    // Runs the thread
    void threadRun();

    int assessQueue();

    void terminateThread();
    
};